"""Add column posible assistances in user_activity

Revision ID: 190ca098557d
Revises: 5bfe3c5b66d9
Create Date: 2024-12-04 08:15:28.540427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190ca098557d'
down_revision: Union[str, None] = '5bfe3c5b66d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('possible_assistance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'possible_assistance')
    # ### end Alembic commands ###
