"""Add level table

Revision ID: cd04e2dee5f7
Revises: 2606e68b6bed
Create Date: 2024-12-10 06:48:50.906040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd04e2dee5f7'
down_revision: Union[str, None] = '2606e68b6bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('range_min', sa.Integer(), nullable=False),
    sa.Column('range_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('level_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'level', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'level_id')
    op.drop_table('level')
    # ### end Alembic commands ###
